# -*- coding: utf-8 -*-
"""Mini Project(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gFSxL-aMn-1mBmwTRoDmPEB_XB0F1w6c

5. Project Option 2: Student Marks Analyzer (Recommended)
5.1 Problem Statement Develop a program that analyzes student marks using Python and
NumPy.
5.2 Functional Requirements The program should:
● Accept marks for multiple students
● Store marks in a NumPy array
● Calculate:
○ Total marks
○ Average marks
○ Highest and lowest marks
● Assign grade based on average
5.3 Grade Logic (Student-Defined) Students must define their own grading rules such as:
● A: Above 85
● B: 70–85
● C: 50–69
● Fail: Below 50 Grades must be implemented using conditional statements.
"""

import numpy as np # import numpy library and store it in the variable called as np.
n = int(input("Enter the number of marks ")) # How many student marks you want.
L = [] # An empty list create.
for i in range(n): # Get a loop till the n.
    marks = int(input("Enter the marks ")) # Input the marks.
    L.append(marks) # Append the marks into the list.
array = np.array(L) # Now create a numpy array.
print(array) # print the array.
total = np.sum(array) # Created a total variable with the sum function.
max = np.max(array) # Created a max variable with the max function.
min = np.min(array) # Created a min variable with the min function.
average = np.mean(array) # Created an average variable with the mean function.
print("Total marks ",total) # Print the total marks.
print("Maximum marks ",max) # Print the maximum marks.
print("Minimum marks ",min) # Print the minimum marks.
print("Average marks ",average) # Print the average marks.
if(average>85): # Condition: average greater than 85
    print("Grade A") # Print Grade A
elif(average<=85 and average>=70): # Condition: average is between 85 and 70
    print("Grade B") # Print Grade B
elif(average<70 and average>=50): # Condition: average is between 69 and 50
    print("Grade C") # Print Grade C
else: # Otherwise
    print("Fail") # Print Fail